function [dx] = Model(t, x, p, inputFunction)

%     p = ModelParameters();

    M_P = x(p.M_P);
    M_C = x(p.M_C);
	M_B = x(p.M_B);
	P_C = x(p.P_C);
	C_C = x(p.C_C);
	P_CP = x(p.P_CP);
	C_CP = x(p.C_CP);
	PC_C = x(p.PC_C);
	PC_N = x(p.PC_N);
	PC_CP = x(p.PC_CP);
	PC_NP = x(p.PC_NP);
	B_C = x(p.B_C);
	B_CP = x(p.B_CP);
	B_N = x(p.B_N);
	B_NP = x(p.B_NP);
	I_N = x(p.I_N);

    input = inputFunction(t, x);

    dx = zeros(length(x), 1);

    % multiplicative input
    dx(p.M_P) = input * p.v_sP * B_N^(p.n) / (p.K_AP^(p.n) + B_N^(p.n)) ...
        - p.v_mP * M_P / (p.K_mP + M_P) ...
        - p.k_dmp * M_P;
%     % additive input
%     dx(p.M_P) = input ...
%         + p.v_sP * B_N^(p.n) / (p.K_AP^(p.n) + B_N^(p.n)) ...
%         - p.v_mP * M_P / (p.K_mP + M_P) ...
%         - p.k_dmp * M_P;
    dx(p.M_C) = p.v_sC * B_N^(p.n) / (p.K_AC^(p.n) + B_N^(p.n)) ...
        - p.v_mC * M_C / (p.K_mC + M_C) ...
        - p.k_dmc * M_C;
    dx(p.M_B) = p.v_sB * p.K_IB^(p.m) / (p.K_IB^(p.m) + B_N^(p.m)) ...
        - p.v_mB * M_B / (p.K_mB + M_B) ...
        - p.k_dmb * M_B;
    dx(p.P_C) = p.k_sP * M_P ...
        - p.V_1P * P_C / (p.K_p + P_C) ...
        + p.V_2P * P_CP / (p.K_dp + P_CP) ...
        + p.k_4 * PC_C ...
        - p.k_3 * P_C * C_C ...
        - p.k_dn * P_C;
    dx(p.C_C) = p.k_sC * M_C ...
        - p.V_1C * C_C / (p.K_p + C_C) ...
        + p.V_2C * C_CP / (p.K_dp + C_CP) ...
        + p.k_4 * PC_C ...
        - p.k_3 * P_C * C_C ...
        - p.k_dnc * C_C;
    dx(p.P_CP) = p.V_1P * P_C / (p.K_p + P_C) ...
        - p.V_2P * P_CP / (p.K_dp + P_CP) ...
        - p.v_dPC * P_CP / (p.K_d + P_CP) ...
        - p.k_dn * P_CP;
    dx(p.C_CP) = p.V_1C * C_C / (p.K_p + C_C) ...
        - p.V_2C * C_CP / (p.K_dp + C_CP) ...
        - p.v_dCC * C_CP / (p.K_d + C_CP) ...
        - p.k_dn * C_CP;
    dx(p.PC_C) = - p.V_1PC * PC_C / (p.K_p + PC_C) ...
        + p.V_2PC * PC_CP / (p.K_dp + PC_CP) ...
        - p.k_4 * PC_C ...
        + p.k_3 * P_C * C_C ...
        + p.k_2 * PC_N ...
        - p.k_1 * PC_C ...
        - p.k_dn * PC_C;
    dx(p.PC_N) = - p.V_3PC * PC_N / (p.K_p + PC_N) ...
        + p.V_4PC * PC_NP / (p.K_dp + PC_NP) ...
        - p.k_2 * PC_N ...
        + p.k_1 * PC_C ...
        - p.k_7 * B_N * PC_N ...
        + p.k_8 * I_N ...
        - p.k_dn * PC_N;
    dx(p.PC_CP) = p.V_1PC * PC_C / (p.K_p + PC_C) ...
        - p.V_2PC * PC_CP / (p.K_dp + PC_CP) ...
        - p.v_dPCC * PC_CP / (p.K_d + PC_CP) ...
        - p.k_dn * PC_CP;
    dx(p.PC_NP) = p.V_3PC * PC_N / (p.K_p + PC_N) ...
        - p.V_4PC * PC_NP / (p.K_dp + PC_NP) ...
        - p.v_dPCN * PC_NP / (p.K_d + PC_NP) ...
        - p.k_dn * PC_NP;
    dx(p.B_C) = p.k_sB * M_B ...
        - p.V_1B * B_C / (p.K_p + B_C) ...
        + p.V_2B * B_CP / (p.K_dp + B_CP) ...
        - p.k_5 * B_C ...
        + p.k_6 * B_N ...
        - p.k_dn * B_C;
    dx(p.B_CP) = p.V_1B * B_C / (p.K_p + B_C) ...
        - p.V_2B * B_CP / (p.K_dp + B_CP) ...
        - p.v_dBC * B_CP / (p.K_d + B_CP) ...
        - p.k_dn * B_CP;
    dx(p.B_N) = - p.V_3B * B_N / (p.K_p + B_N) ...
        + p.V_4B * B_NP / (p.K_dp + B_NP) ...
        + p.k_5 * B_C ...
        - p.k_6 * B_N ...
        - p.k_7 * B_N * PC_N ...
        + p.k_8 * I_N ...
        - p.k_dn * B_N;
    dx(p.B_NP) = p.V_3B * B_N / (p.K_p + B_N) ...
        - p.V_4B * B_NP / (p.K_dp + B_NP) ...
        - p.v_dBN * B_NP / (p.K_d + B_NP) ...
        - p.k_dn * B_NP;
    dx(p.I_N) = - p.k_8 * I_N ...
        + p.k_7 * B_N * PC_N ...
        - p.v_dIN * I_N / (p.K_d + I_N) ...
        - p.k_dn * I_N;

end
